# Site settings
email: vergil000@gmail.com
baseurl: ""
paginate: 7
paginate_path: "/blog/page-:num"
google_analytics: UA-91837424-7

# SEO settings
title: Rang的个人博客
description: Rang's Personal Website.
url: "www.rangluo.win"
#twitter_username: 
default_img: http://olprfwyyd.bkt.clouddn.com/logo_R_shaped.png

# Profile settings
name: Rang's Personal Website.
profile_img: http://olprfwyyd.bkt.clouddn.com/logo_R_shaped.png
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
